(defun meow-setup ()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
  (meow-motion-overwrite-define-key
   '("s" . avy-goto-char-timer)
   '("t" . consult-buffer)
   '("j" . meow-next)
   '("k" . meow-prev)
   '("l" . meow-right)
   '("h" . meow-left)
   '("H" . meow-left-expand)
   '("I" . meow-open-above)
   '("J" . meow-next-expand)
   '("K" . meow-prev-expand)
   '("L" . meow-right-expand)
   '("w" . meow-next-word)
   '("e" . meow-mark-word)
   '("b" . meow-back-word)
   '("g" . meow-cancel-selection)
   '("x" . meow-line)
   '("y" . meow-save)
   '("<escape>" . ignore))
  
  (meow-normal-define-key
   '("M" . consult-mark)
   '("t" . consult-buffer)
   '("s" . avy-goto-char-timer)
   ;; '("C-f" . scroll-up-command)
   ;; '("C-b" . scroll-down-command)
   '("}" . forward-paragraph)
   '("{" . backward-paragraph)
   '("1" . meow-digit-argument)
   '("2" . meow-digit-argument)
   '("3" . meow-digit-argument)
   '("4" . meow-digit-argument)
   '("5" . meow-digit-argument)
   '("6" . meow-digit-argument)
   '("7" . meow-digit-argument)
   '("8" . meow-digit-argument)
   '("9" . meow-digit-argument)
   '("0" . meow-digit-argument)
   '(")" . meow-expand-0)
   '("(" . meow-expand-9)
   '("*" . meow-expand-8)
   '("&" . meow-expand-7)
   '("^" . meow-expand-6)
   '("%" . meow-expand-5)
   '("$" . meow-expand-4)
   '("#" . meow-expand-3)
   '("@" . meow-expand-2)
   '("!" . meow-expand-1)
   '("-" . negative-argument)
   '(";" . exchange-point-and-mark)
   '("," . meow-inner-of-thing)
   '("." . meow-bounds-of-thing)
   '("[" . meow-beginning-of-thing)
   '("]" . meow-end-of-thing)
   '("a" . my-meow-append)
   '("A" . meow-open-below)
   '("b" . meow-back-word)
   '("B" . meow-back-symbol)
   '("c" . meow-change)
   '("D" . meow-kill-whole-line)
   '("f" . meow-find)
   '("F" . consult-grep)
   '("e" . meow-mark-word)
   '("E" . meow-mark-symbol)
   '("g" . meow-cancel-selection)
   '("G" . meow-grab)
   '("h" . meow-left)
   '("H" . meow-left-expand)
   '("i" . meow-insert)
   '("I" . meow-open-above)
   '("j" . meow-next)
   '("J" . meow-next-expand)
   '("k" . meow-prev)
   '("K" . meow-prev-expand)
   '("l" . meow-right)
   '("L" . meow-right-expand)
   '("m" . meow-join)
   '("n" . meow-search)
   ;; '("o" . meow-block)
   ;; '("O" . meow-to-block)
   '("p" . yank)
   '("q" . meow-quit)
   ;; '("S" . avy-goto-line)
   '("T" . meow-swap-grab)
   '("u" . meow-undo)
   '("U" . undo-redo)
   '("v" . meow-visit)
   '("w" . meow-next-word)
   '("W" . meow-next-symbol)
   ;; '("Q" . meow-goto-line)
   ;; '("d" . meow-kill)
   ;; '("U" . meow-undo-in-selection)
   '("x" . meow-line)
   '("X" . meow-goto-line)
   '("y" . meow-save)
   '("M-w" . meow-clipboard-save)
   '("Y" . meow-sync-grab)
   '("z" . meow-pop-selection)
   '("'" . repeat)
   ;; '("'" . kmacro-start-macro-or-insert-counter)
   '("\"" . meow-end-or-call-kmacro)
   '("<escape>" . ignore)
   ;; '("r" . replace-string)
   ;; '("R" . meow-replace)
   ;; '("r" . ((lambda ()
   ;; (interactive)
   ;; (delete-char 1)  ;; 删除当前字符
   ;; (insert (read-char "Replace with: ")) ;; 提示用户输入字符并插入
   ;; )))
   '("/" . isearch-forward)
   '("n" . meow-search)
   '("N" . isearch-repeat-backward)
   '("=" . indent-region))
  
  (meow-leader-define-key
   ;; SPC j/k will run the original command in MOTION state.
   '("j" . "H-j")
   '("k" . "H-k")
   ;; Use SPC (0-9) for digit arguments.
   '("0" . delete-window)
   '("1" . delete-other-windows)
   '("2" . split-window-below)
   '("3" . split-window-right)
   '("4" . switch-to-buffer-other-frame)
   '("/" . meow-keypad-describe-key)
   '("?" . meow-cheatsheet)
   ;; '("b" . consult-buffer)
   ;; '("s" . meow-block)
   '("SPC" . (lambda () (interactive) (switch-to-buffer "*scratch*")))
   '("d" . (lambda () (interactive) (switch-to-buffer "*dashboard*")))
   '("e" . (lambda () (interactive) (find-file "~/.emacs.d/lisp/")))
   '("w" . ace-window)
   '("r" . revert-buffer)
   '("S" . surround-insert)
   '("C" . surround-change)
   '("K" . surround-kill)
   '("q" . save-buffers-kill-terminal)))

(use-package meow
  :init
  (meow-global-mode 1)
  :config
  (meow-setup)
  (meow-setup-line-number)
  (setq meow-use-cursor-position-hack t
        meow-use-enhanced-selection-effect t)  ;; optional, for visual effect
  (setopt meow-use-clipboard nil
          ;; meow-expand-hint-counts nil
          ))

(defun my-meow-fix-empty-eof-advice (&rest _args)
  "修复 meow-change 在行尾或 EOF 处无法使用及光标块状的 bug。"
  (when (and (not (region-active-p)) ; 只有在没有手动选中时才干预
             (eolp))                ; 处于行尾（包含你说的 EOF 空行和最后一个字符后）
    ;; 技巧：插入一个临时空格并把光标移上去
    ;; 这样随后的 meow-change 就会‘改变’这个空格（删除它并进入插入模式）
    ;; 这能完美触发 Meow 的状态切换机制，解决块状光标和无法退出的问题
    (insert " ")
    (backward-char 1)))

;; 维持原有的 advice 绑定
(advice-add 'meow-change :before #'my-meow-fix-empty-eof-advice)